# Generated by Django 2.1.1 on 2019-01-31 12:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('country', models.CharField(max_length=120)),
                ('city', models.CharField(max_length=120)),
                ('desc', models.CharField(max_length=120)),
                ('temp', models.FloatField()),
                ('humidity', models.IntegerField()),
                ('wind_speed', models.FloatField()),
                ('icon', models.CharField(max_length=120)),
            ],
        ),
    ]
