# Generated by Django 2.1.1 on 2019-01-22 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=120)),
                ('name', models.CharField(max_length=120)),
                ('weather_desc', models.CharField(max_length=120)),
                ('temp', models.FloatField()),
                ('humidity', models.IntegerField()),
                ('wind_speed', models.FloatField()),
                ('weather_icon', models.CharField(max_length=120)),
            ],
        ),
        migrations.DeleteModel(
            name='Article',
        ),
    ]
