# Generated by Django 2.1.1 on 2019-01-30 10:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='last_update',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='weather',
            name='units',
            field=models.CharField(choices=[('K', 'kelvin'), ('C', 'celsius'), ('F', 'fahrenheit')], default='K', max_length=2),
        ),
        migrations.AlterField(
            model_name='weather',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
