# Generated by Django 2.1.1 on 2019-01-30 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20190130_1019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weather',
            name='last_update',
        ),
    ]
